# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Phat Le/DataPath/DataPath.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Phat Le/DataPath/DataPath.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Phat Le/DataPath/DataPath.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Phat Le/DataPath/DataPath.srcs/sources_1/new/CU.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/CMPE 125 Lab 7 Small Calculator DP Source Code/CMPE 125 Lab 7 Small Calculator DP Source Code/alu.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/bcd_to_7seg.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/binary2bcd.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/basys3_utility_modules/basys3_utility_modules/button_debouncer.v}
  {C:/Users/Phat Le/DataPath/DataPath.srcs/sources_1/new/calculatorFPGA.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/clk_gen.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/led_mux.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/CMPE 125 Lab 7 Small Calculator DP Source Code/CMPE 125 Lab 7 Small Calculator DP Source Code/mux2.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/CMPE 125 Lab 7 Small Calculator DP Source Code/CMPE 125 Lab 7 Small Calculator DP Source Code/mux4.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/CMPE 125 Lab 7 Small Calculator DP Source Code/CMPE 125 Lab 7 Small Calculator DP Source Code/register_file.v}
  {C:/Users/Phat Le/Desktop/Fall2019/CMPE125/CMPE 125 Lab 7 Small Calculator DP Source Code/CMPE 125 Lab 7 Small Calculator DP Source Code/small_calculator_dp.v}
  {C:/Users/Phat Le/DataPath/DataPath.srcs/sources_1/new/FPGA.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Phat Le/DataPath/DataPath.srcs/constrs_1/new/calculator_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Phat Le/DataPath/DataPath.srcs/constrs_1/new/calculator_constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FPGA -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FPGA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FPGA_utilization_synth.rpt -pb FPGA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
